---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-prod-wrk-deployment
  labels:
    app: stocks-prod-wrk
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stocks-prod-wrk
  template:
    metadata:
      labels:
        app: stocks-prod-wrk
        env: prod
    spec:
      containers:
        - name: stocks-prod-wrk
          image: stevendiep/stocks-test-worker:1.0
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: ${RIP}
